### ISSUE TITLE
rn.resolve schema 配置有误

### ISSUE THREAD

**Issue by shinken008** [NervJS/taro-doctor#2]
https://github.com/NervJS/taro-doctor/blob/f3ce6b6523faf9b87f3e8bc5edaecbf376f1c304/assets/config_schema.json#L960

https://taro-docs.jd.com/docs/config-detail#rnresolve

参考文档，rn.resolve 里面有个 include 然后再是数组，schema 配置有误。

**Comment by shinken008** [comment]
https://github.com/NervJS/taro/issues/14047#issuecomment-1600249026

**Comment by luckyadam** [comment]
修复了这个 schema，0.0.10 后版本的 taro-doctor 会自动拉取这个项目的 schema 文件来做校验，所以 taro-doctor 不用发版本，不过目前需要 Taro 发个版本，更新到最新的  taro-doctor 版本的引用
