### ISSUE TITLE
mini.optimizeMainPackage.exclude 报错

### ISSUE THREAD

**Issue by evoforce** [NervJS/taro-doctor#3]
参考了官方文档
`module.exports = {
  // ...
  mini: {
    // ...
    optimizeMainPackage: {
      enable: true,
      exclude: [path.resolve(__dirname, 'moduleName.js'), (module) => module.resource.indexOf('moduleName') >= 0],
    },
  },
}`

taro3.6.8启动报错
mini.optimizeMainPackage.exclude.1 的值 "__function__" 不满足要求的格式

**Comment by ZakaryCode** [comment]
Duplicate of #5

**Comment by july0729** [comment]
module.resource?.indexOf,module.resource可能是undefined
